@echo off
REM Setup script to fetch API keys from GCP Secret Manager and create .env file
REM Windows version

echo.
echo ================================
echo Kaimi Environment Setup
echo ================================
echo.

REM Check if gcloud is installed
where gcloud >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] gcloud CLI is not installed
    echo         Install from: https://cloud.google.com/sdk/docs/install
    exit /b 1
)

REM Set project to kaimi-seeker
echo Setting project to kaimi-seeker...
gcloud config set project kaimi-seeker

REM Get current account
for /f "delims=" %%a in ('gcloud config get-value account 2^>nul') do set ACCOUNT=%%a
echo [OK] Authenticated as: %ACCOUNT%
echo [OK] Project: kaimi-seeker
echo.

REM Fetch secrets from Secret Manager
echo Fetching secrets from Secret Manager...

for /f "delims=" %%a in ('gcloud secrets versions access latest --secret=samgov-api-key 2^>nul') do set SAM_API_KEY=%%a
if "%SAM_API_KEY%"=="" (
    echo [ERROR] Could not fetch samgov-api-key
    echo         Make sure you have Secret Manager access
    exit /b 1
)
echo [OK] Retrieved SAM.gov API key

for /f "delims=" %%a in ('gcloud secrets versions access latest --secret=google-ai-studio-api-key 2^>nul') do set GOOGLE_API_KEY=%%a
if "%GOOGLE_API_KEY%"=="" (
    echo [ERROR] Could not fetch google-ai-studio-api-key
    echo         Make sure you have Secret Manager access
    exit /b 1
)
echo [OK] Retrieved Google AI Studio API key

REM Create .env file
echo.
echo Creating .env file...

(
echo # Kaimi Environment Configuration
echo # Auto-generated by scripts/setup-env.bat
echo # DO NOT COMMIT THIS FILE
echo.
echo # SAM.gov API Key
echo SAM_API_KEY=%SAM_API_KEY%
echo.
echo # Google AI Studio API Key ^(for Gemini agent platform - ADK Go^)
echo GOOGLE_API_KEY=%GOOGLE_API_KEY%
echo.
echo # Hunter Configuration ^(optional - can also use command-line flags^)
echo # MODE=cached
echo # NAICS_CODES=541512,541519
echo # STORE_PATH=./queue
) > .env

echo [OK] Created .env file
echo.
echo ================================
echo Setup complete!
echo ================================
echo.
echo Your environment is ready. The .env file has been created with:
echo   - SAM_API_KEY
echo   - GOOGLE_API_KEY
echo.
echo To use these in your current terminal session, run:
echo   set GOOGLE_API_KEY=%GOOGLE_API_KEY%
echo   set SAM_API_KEY=%SAM_API_KEY%
echo.
echo Or they will be loaded automatically when you run the application.
echo.

pause
